name: eko_messenger
description: "A new Flutter project."
publish_to:

version: 0.0.4+4

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^17.0.0
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  hooks_riverpod: ^3.0.3
  ecp:
    # path: ../ecp-dart-sdk
    git:
      url: https://github.com/eko-network/ecp-dart-sdk
      ref: 95b7bd7e87788ed5890f78d850241706d43edbf8
  flutter_secure_storage: ^9.2.4
  path_provider: ^2.1.5
  drift: ^2.28.2
  sqlite3: ^2.9.4
  path: ^1.9.1
  sqlcipher_flutter_libs: ^0.6.8
  http: ^1.2.1
  device_info_plus: ^12.3.0
  shadcn_ui: ^0.43.0
  collection: ^1.19.1
  uuid: ^4.5.2
  flutter_local_notifications: 19.5.0
  unifiedpush: ^6.2.0
  package_info_plus: ^9.0.0
  intl: ^0.20.2
  characters: ^1.4.0

dev_dependencies:
  drift_dev: ^2.28.0
  build_runner: ^2.5.4
  riverpod_generator: ^3.0.3
  flutter_launcher_icons: ^0.14.2

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
  # assets:
  #   - branding/logo.png

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf
        - asset: assets/fonts/Inter-Italic.ttf

    - family: NotoEmoji
      fonts:
        - asset: assets/fonts/NotoColorEmoji.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "branding/logo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "branding/logo.png"
  macos:
    generate: true
    image_path: "branding/logo.png"
