name: build
on:
  workflow_call:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build Linux
        run: |
          nix develop .#default --command flutter build linux --release \
          --dart-define KLIPY_API_KEY=${{ secrets.KLIPY_API_KEY }}
      - name: Package Linux Build (Tarball)
        run: |
          cd build/linux/x64/release/bundle/
          tar -cJf ../../../../linux-release.tar.xz .
          cd -
      - name: Decode Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks
      - name: Remove NotoEmoji
        run: nix run nixpkgs#yq-go -- eval -i 'del(.flutter.fonts[] | select(.family == "NotoEmoji"))' pubspec.yaml
      - name: Build Signed APK and App Bundle
        run: |
          nix develop .#default --command flutter build apk --release \
          --dart-define KLIPY_API_KEY=${{ secrets.KLIPY_API_KEY }}
          nix develop .#default --command flutter build appbundle --release \
          --dart-define KLIPY_API_KEY=${{ secrets.KLIPY_API_KEY }}
        env:
          ANDROID_KEYSTORE_PATH: upload-keystore.jks
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      - name: Reset Repo
        run: |
          git reset --hard
      - name: Install Cider
        run: dart pub global activate cider
      - name: Bump Version
        run: |
          ~/.pub-cache/bin/cider bump patch
          ~/.pub-cache/bin/cider bump build
